services:
  db:
    container_name: neoCustomers_pg
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - neoCustomers_network

volumes:
  postgres-data:
    driver: local

networks:
  neoCustomers_network:
    driver: bridge