spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret:
      key: ${JWT_SECRET_KEY}
    expiration:
      minutes: ${JWT_EXPIRATION_MINUTES}