spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  jwt:
    secret:
      key: ${JWT_SECRET_KEY}
    expiration:
      minutes: ${JWT_EXPIRATION_MINUTES}