spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registrapi_dev
    username: postgres_dev
    password: dev_secret

admin:
  default:
    email: admin-dev@neoapp.com
    password: dev123